server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3389/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
debug: false
logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: ERROR